set(CMAKE_INSTALL_MESSAGE LAZY)

set(HAYAI_PREFIX "${CMAKE_CURRENT_BINARY_DIR}/externals/hayai")
set(HAYAI_INSTALL_SUBFOLDER "src/hayai-install")
set(HAYAI_INSTALL_PREFIX "${HAYAI_PREFIX}/${HAYAI_INSTALL_SUBFOLDER}")

ExternalProject_Add(
        hayai-prj
        GIT_REPOSITORY https://github.com/nickbruun/hayai.git
	GIT_TAG master
        PREFIX "${HAYAI_PREFIX}"
	LOG_INSTALL OFF
	LOG_BUILD OFF
	LOG_CONFIGURE OFF
        BUILD_BYPRODUCTS  ${HAYAI_INSTALL_PREFIX}/lib/${CMAKE_FIND_LIBRARY_PREFIXES}hayai_main.a
	CMAKE_ARGS
	-DBUILD_HAYAI_SAMPLES=OFF
	-DBUILD_HAYAI_TESTS=OFF
	-DCMAKE_INSTALL_PREFIX=${HAYAI_INSTALL_PREFIX}
	-DCMAKE_INSTALL_MESSAGE:STRING=LAZY
        -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
)

set(HAYAI_INCLUDE_DIRS ${HAYAI_INSTALL_PREFIX}/include)

set(HAYAI_LIBRARY_PATH ${HAYAI_INSTALL_PREFIX}/lib/${CMAKE_FIND_LIBRARY_PREFIXES}hayai_main.a)
set(HAYAI_LIBRARY hayai)

add_library(${HAYAI_LIBRARY} UNKNOWN IMPORTED)
set_target_properties(${HAYAI_LIBRARY} PROPERTIES
   "IMPORTED_LOCATION" "${HAYAI_LIBRARY_PATH}"
   "IMPORTED_LINK_INTERFACE_LIBRARIES" "${CMAKE_THREAD_LIBS_INIT}"
)

add_dependencies(${HAYAI_LIBRARY} hayai-prj)

